# Generated by Django 6.0.4 on 2026-05-07 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_employee_alter_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='img',
            field=models.ImageField(upload_to='employees/'),
        ),
    ]
