# Generated by Django 6.0.4 on 2026-05-09 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_salarylog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='img',
        ),
        migrations.CreateModel(
            name='EmployeeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='empployees/')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.employee')),
            ],
        ),
    ]
