# Generated by Django 6.0.4 on 2026-05-09 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_employee_img_employeeimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeimage',
            name='images',
            field=models.ImageField(upload_to='employees/'),
        ),
    ]
