# Generated by Django 6.0.4 on 2026-05-11 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_employeeimage_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeimage',
            name='id',
        ),
        migrations.AddField(
            model_name='employeeimage',
            name='img_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
