# Generated by Django 6.0.4 on 2026-05-14 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_employee_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeimage',
            name='employee',
        ),
        migrations.DeleteModel(
            name='Salarylog',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='EmployeeImage',
        ),
    ]
